#!/usr/bin/env python

import rospy

from dynamic_reconfigure.server import Server
from emcl.cfg import dynamicConfig 
#The name TutorialsConfig is automatically generated by appending Config to the 3rd argument in gen.generate

def callback(config, level):
    rospy.loginfo("""Reconfigure Request: {odom_fw_dev_per_fw}, {odom_fw_dev_per_rot},{odom_rot_dev_per_fw}, {odom_rot_dev_per_rot}""".format(**config))
    rospy.set_param('/emcl_node/odom_fw_dev_per_fw', float("{odom_fw_dev_per_fw}".format(**config)))
    rospy.set_param('/emcl_node/odom_fw_dev_per_rot', float("{odom_fw_dev_per_rot}".format(**config)))
    rospy.set_param('/emcl_node/odom_rot_dev_per_fw', float("{odom_rot_dev_per_fw}".format(**config)))
    rospy.set_param('/emcl_node/odom_rot_dev_per_rot', float("{odom_rot_dev_per_rot}".format(**config)))

    return config

if __name__ == "__main__":
    rospy.init_node("emcl_dynamic", anonymous = False)
    srv = Server(dynamicConfig, callback)
    rospy.spin()